In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]


In [3]:
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)

Shape of A: (2, 2)
Shape of B: (2, 2)


In [4]:
result = np.dot(A, B)
print("A × B =")
print(result)

A × B =
[[19 22]
 [43 50]]


In [5]:
# A non-square example
C = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2x3

D = np.array([[7,  8],
              [9,  10],
              [11, 12]])    # 3x2

result2 = np.dot(C, D)
print("Shape of C:", C.shape)
print("Shape of D:", D.shape)
print("Result shape:", result2.shape)
print(result2)

Shape of C: (2, 3)
Shape of D: (3, 2)
Result shape: (2, 2)
[[ 58  64]
 [139 154]]


In [6]:
# 3 patients, each with 3 risk factors (age_scaled, sbp_scaled, smoking)
patients = np.array([[0.8, 1.2, 1.0],
                     [0.5, 0.9, 0.0],
                     [1.1, 1.4, 1.0]])

# Coefficients for each risk factor
coefficients = np.array([0.5, 0.3, 0.8])

# One matrix multiplication → risk scores for ALL patients simultaneously
risk_scores = np.dot(patients, coefficients)
print("Risk scores:", risk_scores)

Risk scores: [1.56 0.52 1.77]


In [1]:
import numpy as np

B = np.array([[2, 1],
              [5, 3]])

B_inv = np.linalg.inv(B)

print("B inverse:")
print(B_inv)

print("\nB × B_inv (should be identity):")
print(np.round(np.dot(B, B_inv)))

B inverse:
[[ 3. -1.]
 [-5.  2.]]

B × B_inv (should be identity):
[[1. 0.]
 [0. 1.]]


In [3]:
import numpy as np

D = np.array([[3, 6],
              [2, 4]])

print("Determinant:", np.linalg.det(D))
print("Is singular?", np.isclose(np.linalg.det(D), 0))

try:
    D_inv = np.linalg.inv(D)
    print(D_inv)
except np.linalg.LinAlgError as e:
    print("Error:", e)

Determinant: 6.66133814775094e-16
Is singular? True
[[ 6.00479950e+15 -9.00719925e+15]
 [-3.00239975e+15  4.50359963e+15]]
